# ==========================================
# database_management/storage_engines/__init__.py
# save-state: 2026-07-13T10:57-04:00
# Package exposure layer for storage abstractions
# ==========================================
import logging
from .postgres_engine import PostgresStorageEngine

logger = logging.getLogger(__name__)

class StorageEngineFactory:
    @staticmethod
    def get_engine(engine_type: str, **kwargs):
        """
        Unified factory router to satisfy core/database.py initialization.
        Binds the submissive engine instances based on the requested environment token.
        """
        normalized_type = str(engine_type).strip().upper()
        
        if normalized_type == "POSTGRES":
            # Extract the pool connection generated by psycopg_pool in database.py
            pool = kwargs.get("connection_pool") or kwargs.get("pool")
            if not pool:
                raise ValueError("Cannot initialize POSTGRES engine without a valid connection pool.")
            
            logger.debug("Instantiating PostgresStorageEngine relational worker mapping.")
            return PostgresStorageEngine(pool=pool)
            
        elif normalized_type == "FLAT_FILE":
            # core/database.py catches ImportError for FLAT_FILE to intentionally 
            # fall back to its internal local file tracking routines.
            # Raising an ImportError here guarantees that the offline mock works cleanly.
            raise ImportError("FLAT_FILE target handled by internal system fallbacks.")
            
        else:
            raise ValueError(f"Unsupported storage engine footprint requested: {engine_type}")